shelter: refine to support initrd and disk images
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>

diff --git a/shelter b/shelter
--- a/shelter
+++ b/shelter
@@ -5,12 +5,14 @@
 SHELTER_CONF="/etc/shelter.conf"
 SHELTER_CONF_DIR="/etc/shelter.d"
 SHELTER_INITRD_CONF_DIR="${SHELTER_CONF_DIR}/initrd"
+SHELTER_DISK_CONF_DIR="${SHELTER_CONF_DIR}/disk"
+
 SHELTER_DEFAULT_STAGE="default"
 SHELTER_STAGE_DIR="/var/run/shelter/${SHELTER_DEFAULT_STAGE}"
 SHELTER_INITRD="${SHELTER_STAGE_DIR}/initrd"
 SHELTER_KERNEL="${SHELTER_STAGE_DIR}/kernel"
-SHELTER_PHRASE="${SHELTER_STAGE_DIR}/phrase"
 SHELTER_DISK="${SHELTER_STAGE_DIR}/disk"
+SHELTER_PASSPHRASE="${SHELTER_STAGE_DIR}/passphrase"
 
 EXTRA_DIR="${SHELTER_STAGE_DIR}/extra"
 CONF="${SHELTER_STAGE_DIR}/build.conf"
@@ -52,9 +54,11 @@ randomize() {
     done
 }
 
-create_phrase() {
-    dd if=/dev/urandom of=${SHELTER_PHRASE} bs=1K count=1
-    chmod 600 ${SHELTER_PHRASE}
+create_passphrase() {
+    debug "Creating LUKS passphrase"
+
+    dd if=/dev/urandom of=${SHELTER_PASSPHRASE} bs=1K count=1
+    chmod 600 ${SHELTER_PASSPHRASE}
 }
 
 add_dir() {
@@ -186,6 +190,10 @@ build() {
         warn "WARNING: Running shelter build with root privileges is generally necessary. Try `sudo su -`."
     fi
 
+    # The default image type is initrd
+    local image_type="$(get_conf image_type)"
+    image_type="${image_type:=initrd}"
+
     while [[ $# -gt 0 ]]; do
         case "$1" in
             -c|--config)
@@ -201,6 +209,14 @@ build() {
                     return 1
                 fi
                 ;;
+            -T|--image-type)
+                if [ "$2" != "initrd" && "$2" != "disk" ]; then
+                    error "Error: invalid -T|--image-type value." >&2
+                    return 1
+                fi
+                image_type="$2"
+                shift
+                ;;
             *)
                 error "Unrecognized option $1"
                 return 1
@@ -209,7 +225,7 @@ build() {
         shift
     done
 
-    debug "Gather files to be copied to initrd and copy into $EXTRA_DIR"
+    debug "Gather files to be copied and copy into $EXTRA_DIR"
     rm -rf "$EXTRA_DIR"
 
     if [ ! -d "$EXTRA_DIR" ]; then
@@ -263,18 +279,22 @@ build() {
 
     local kernel_version="$(uname -r)"
 
-    debug "Building initrd image: ${SHELTER_INITRD}"
-    mkosi -f --debug -C "${SHELTER_INITRD_CONF_DIR}" \
-    --postinst-script="${SHELTER_INITRD_CONF_DIR}/mkosi.postinst" \
-    --output-dir="${SHELTER_STAGE_DIR}" --output="$(basename ${SHELTER_INITRD})" \
-    --extra-tree="${EXTRA_DIR}:/extra" \
-    --extra-tree="/usr/lib/modules/${kernel_version}:/usr/lib/modules/${kernel_version}" \
-    build
+    if [ "$image_type" = "disk" ]; then
+        debug "Building initrd image: ${SHELTER_INITRD}"
 
-    if [ $? -ne 0 ]; then
-        error "Error: failed to build initrd image with mkosi"
-        exit 1
+        mkosi -f --debug -C "${SHELTER_INITRD_CONF_DIR}" \
+          --postinst-script="${SHELTER_INITRD_CONF_DIR}/mkosi.postinst" \
+          --output-dir="${SHELTER_STAGE_DIR}" --output="$(basename ${SHELTER_INITRD})" \
+          --extra-tree="${EXTRA_DIR}:/extra" \
+          --extra-tree="/usr/lib/modules/${kernel_version}:/usr/lib/modules/${kernel_version}" \
+          build
+
+        if [ $? -ne 0 ]; then
+            error "Error: failed to build initrd with mkosi"
+            exit 1
+        fi
     fi
+
     # Parse the mapping between the source and destinaion
     for i in "${binaries[@]}"; do
         if [[ "$i" == *:* ]]; then
@@ -317,25 +337,45 @@ build() {
         copy_file_and_dir_no_resolve_symlink "$i"
     done
 
-    debug "Create luks keyfile"
-    create_phrase
+    if [ "$image_type" = "initrd" ]; then
+        debug "Building initrd image: ${SHELTER_INITRD}"
 
-    debug "Building Disk image: ${SHELTER_DISK}"
-    mkosi -f --debug -C "${SHELTER_CONF_DIR}" \
-      --build-script="${SHELTER_CONF_DIR}/mkosi.build" \
-      --finalize-script="${SHELTER_CONF_DIR}/mkosi.finalize" \
-      --postinst-script="${SHELTER_CONF_DIR}/mkosi.postinst" \
-      --output-dir="${SHELTER_STAGE_DIR}" --output="$(basename ${SHELTER_DISK})" \
-      --extra-tree="${EXTRA_DIR}:/extra" \
-      --extra-tree="/usr/lib/modules/${kernel_version}:/usr/lib/modules/${kernel_version}" \
-      --passphrase="${SHELTER_PHRASE}" \
-      --repart-dir="${SHELTER_CONF_DIR}/mkosi.repart" \
-      build
-      
-    if [ $? -ne 0 ]; then
-        error "Error: failed to build disk image with mkosi"
-        exit 1
+        mkosi -f --debug -C "${SHELTER_INITRD_CONF_DIR}" \
+          --build-script="${SHELTER_INITRD_CONF_DIR}/mkosi.build" \
+          --finalize-script="${SHELTER_INITRD_CONF_DIR}/mkosi.finalize" \
+          --postinst-script="${SHELTER_INITRD_CONF_DIR}/mkosi.postinst" \
+          --output-dir="${SHELTER_STAGE_DIR}" --output="$(basename ${SHELTER_INITRD})" \
+          --extra-tree="${EXTRA_DIR}:/extra" \
+          --extra-tree="/usr/lib/modules/${kernel_version}:/usr/lib/modules/${kernel_version}" \
+          build
+
+        if [ $? -ne 0 ]; then
+            error "Error: failed to build initrd image with mkosi"
+            exit 1
+        fi
+    elif [ "$image_type" = "disk" ]; then
+        create_passphrase
+
+        debug "Building Disk image: ${SHELTER_DISK}"
+
+        mkosi -f --debug -C "${SHELTER_DISK_CONF_DIR}" \
+          --build-script="${SHELTER_DISK_CONF_DIR}/mkosi.build" \
+          --finalize-script="${SHELTER_DISK_CONF_DIR}/mkosi.finalize" \
+          --postinst-script="${SHELTER_DISK_CONF_DIR}/mkosi.postinst" \
+          --output-dir="${SHELTER_STAGE_DIR}" --output="$(basename ${SHELTER_DISK})" \
+          --extra-tree="${EXTRA_DIR}:/extra" \
+          --extra-tree="/usr/lib/modules/${kernel_version}:/usr/lib/modules/${kernel_version}" \
+          --passphrase="${SHELTERPASS}" \
+          --repart-dir="${SHELTER_DISK_CONF_DIR}/mkosi.repart" \
+          build
+
+        if [ $? -ne 0 ]; then
+            error "Error: failed to build disk image with mkosi"
+            exit 1
+        fi
     fi
+
+    store_stage "image_type" "${image_type}"
 
     debug "Copying kernel: ${SHELTER_KERNEL}"
 
@@ -385,68 +425,92 @@ config_qemu() {
 -kernel '${SHELTER_KERNEL}' -initrd '${SHELTER_INITRD}'
 -append '${kern_cmd}'
 -device vhost-vsock-pci,guest-cid=${cid}
--drive file='${SHELTER_DISK}',format=raw,if=virtio
 EOF
 )"
+
+    local image_type="$(get_stage image_type)"
+    if [ x"$image_type" = x"disk" ]; then
+        opts="${opts} -drive file='${SHELTER_DISK}',format=raw,if=virtio"
+    fi
+
     echo -n "${bin} ${opts} ${extra_opts}"
 }
 
 start() {
+    if [ x"$(get_stage image_type)" = x"" ]; then
+        error "The file ${SHELTER_STAGE_DIR}/image_type is missing. You may need to run 'shelter build' first."
+        exit 1
+    fi
+
+    if [ ! -s "${SHELTER_KERNEL}" ]; then
+        error "The file ${SHELTSHELTER_KERNELER_INITRD} is missing. You may need to run 'shelter build' first."
+        exit 1
+    fi
+
+    if [ ! -s "${SHELTER_INITRD}" ]; then
+        error "The file ${SHELTER_INITRD} is missing. You may need to run 'shelter build' first."
+        exit 1
+    fi
+
     local max_user_ns="$(sysctl --binary --quiet user.max_user_namespaces)"
 
     # Work around the default zero max_user_namespaces value on apasa
-    if [ "${max_user_ns}" == "0" ]; then
+    if [ "${max_user_ns}" = "0" ]; then
         warn "Set user.max_user_namespaces to be 766996 forcibly."
         sysctl --write user.max_user_namespaces=766996
     fi
-    
-    if [[ -s "${SHELTER_INITRD}" && -s "${SHELTER_DISK}" && -s "${SHELTER_KERNEL}" ]]; then
-        local cid=$(randomize)
-        store_stage "cid" "${cid}"
 
-        local vmm="$(get_conf vmm)"
-        local cmd=""
-        if [ x"${vmm}" = x"qemu" ]; then
-            local bin="$(get_conf ${vmm}.bin)"
-            local mem="$(get_conf ${vmm}.mem)"
-            local kern_cmdline="$(get_conf ${vmm}.kern_cmdline)"
-            local opts="$(get_conf ${vmm}.opts)"
+    local cid=$(randomize)
+    store_stage "cid" "${cid}"
 
-            cmd="$(config_qemu "${bin}" "${mem}" "${kern_cmdline}" "${cid}" "${opts}")"
+    local vmm="$(get_conf vmm)"
+    local cmd=""
+    if [ x"${vmm}" = x"qemu" ]; then
+        local bin="$(get_conf ${vmm}.bin)"
+        local mem="$(get_conf ${vmm}.mem)"
+        local kern_cmdline="$(get_conf ${vmm}.kern_cmdline)"
+        local opts="$(get_conf ${vmm}.opts)"
+
+        cmd="$(config_qemu "${bin}" "${mem}" "${kern_cmdline}" "${cid}" "${opts}")"
+    fi
+
+    debug "qemu command: $cmd"
+    eval cmd=("$cmd")
+
+    systemd-run --user --description=Shelter --unit=shelter.service -p StandardInput=null -G "${cmd[@]}"
+    if [ $? -ne 0 ]; then
+        error "Failed to run systemd-run to launch qemu."
+        exit 1
+    fi
+
+    debug "The guest is started at CID ${cid}"
+
+    if [ x"$(get_stage image_type)" != x"disk" ]; then
+        return 0
+    fi
+
+    local wait_seconds=${SHELTER_TIMEOUT}
+    debug "Now waiting ${wait_seconds} seconds for the guest to open crypt disk ..."
+    local is_ready=0
+
+    for ((i=${wait_seconds}; i>0; i--)); do
+        if ! is-active; then
+            error "Failed to run shelter guest"
+            return 1
         fi
 
-        debug "qemu command: $cmd"
-        eval cmd=("$cmd")
-
-        systemd-run --user --description=Shelter --unit=shelter.service -p StandardInput=null -G "${cmd[@]}"
-
-        local wait_seconds=${SHELTER_TIMEOUT}
-        debug "Now waiting ${wait_seconds} seconds for the guest to open crypt disk ..."
-        local is_ready=0
-        
-        for ((i=${wait_seconds}; i>0; i--))
-        do
-            if ! is-active; then
-                error "Failed to run shelter guest"
-                return 1
-                fi
-        
-            if socat -u file:${SHELTER_PHRASE} vsock-connect:${cid}:4321 1>&- 2>&-; then
-                # The guest is ready
-                is_ready=1
-                break
-            fi
-                sleep 1
-        done
-
-        if [[ $is_ready -ne 1 ]]; then
-            error "Failed to open shelter guest disk"
-            stop
-            exit 1
+        if socat -u file:${SHELTER_PASSPHRASE} vsock-connect:${cid}:4321 1>&- 2>&-; then
+            # The guest is ready
+            is_ready=1
+            break
         fi
-        debug "The guest is started at CID ${cid}"
-    else
-        error "The files ${SHELTER_INITRD} or ${SHELTER_KERNEL} or ${SHELTER_DISK} is missing. You may need to run 'shelter build' first."
+
+        sleep 1
+    done
+
+    if [ $is_ready -ne 1 ]; then
+        error "Failed to open shelter guest disk"
+        stop
         exit 1
     fi
 }
