Revert "refactor: remove kernel copy logic"
This reverts commit 4af33c213a4509a28e4970161f0bc296de7138b2.

diff --git a/shelter b/shelter
--- a/shelter
+++ b/shelter
@@ -8,7 +8,7 @@ SHELTER_INITRD_CONF_DIR="${SHELTER_CONF_DIR}/initrd"
 SHELTER_DEFAULT_STAGE="default"
 SHELTER_STAGE_DIR="/var/run/shelter/${SHELTER_DEFAULT_STAGE}"
 SHELTER_INITRD="${SHELTER_STAGE_DIR}/initrd"
-SHELTER_KERNEL="${SHELTER_INITRD}.vmlinuz"
+SHELTER_KERNEL="${SHELTER_STAGE_DIR}/kernel"
 SHELTER_PHRASE="${SHELTER_STAGE_DIR}/phrase"
 SHELTER_DISK="${SHELTER_STAGE_DIR}/disk"
 
@@ -323,6 +323,7 @@ build() {
     debug "Building Disk image: ${SHELTER_DISK}"
     mkosi -f --debug -C "${SHELTER_CONF_DIR}" \
       --build-script="${SHELTER_CONF_DIR}/mkosi.build" \
+      --finalize-script="${SHELTER_CONF_DIR}/mkosi.finalize" \
       --postinst-script="${SHELTER_CONF_DIR}/mkosi.postinst" \
       --output-dir="${SHELTER_STAGE_DIR}" --output="$(basename ${SHELTER_DISK})" \
       --extra-tree="${EXTRA_DIR}:/extra" \
@@ -335,6 +336,16 @@ build() {
         error "Error: failed to build disk image with mkosi"
         exit 1
     fi
+
+    debug "Copying kernel: ${SHELTER_KERNEL}"
+
+    if [ -s "/boot/vmlinuz-${kernel_version}" ]; then
+        cp -f "/boot/vmlinuz-${kernel_version}" "${SHELTER_KERNEL}"
+        return 0
+    fi
+
+    error "Error: can't find the currently active kernel from /boot/"
+    exit 1
 }
 
 get_conf() {
