Shelter: support remote attestation

diff --git a/images/disk/init b/images/disk/init
--- a/images/disk/init
+++ b/images/disk/init
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+PATH=$PATH:/usr/local/bin
+
 BUSYBOX="/usr/bin/busybox"
 [ ! -x "$BUSYBOX" ] && BUSYBOX="/usr/sbin/busybox"
 
@@ -23,7 +25,16 @@ if [ -e /proc/sys/kernel/hotplug ]; then
 fi
 mdev -d || mdev -s
 
-socat vsock-listen:4321 "system:'cryptsetup open -d - /dev/vda1 root',nofork"
+# try to config network
+iplink set eth0 up
+udhcpc
+
+kbs-client --url $KBS_URL get-resource --path $PASSPHRASE_PATH | base64 -d | cryptsetup open -d - /dev/vda1 root
+
+if [ $? -ne 0 ]; then
+    echo "luks2 open failed!!"
+    exec init
+fi
 
 mount -t ext4 /dev/mapper/root /mnt
 
