Shelter: support encrypted passphrase bundle
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>

diff --git a/images/disk/init b/images/disk/init
--- a/images/disk/init
+++ b/images/disk/init
@@ -29,12 +29,29 @@ mdev -d || mdev -s
 ip link set eth0 up
 udhcpc -s /usr/share/udhcpc/default.script
 
-if grep -q "KBS_URL=" /proc/cmdline && grep -q "PASSPHRASE_PATH=" /proc/cmdline; then
-    kbs-client --url $KBS_URL get-resource --path $PASSPHRASE_PATH | base64 -d | cryptsetup open -d - /dev/vda1 root
+if ! grep -q "KBS_URL=" /proc/cmdline || ! grep -q "PASSPHRASE_PATH=" /proc/cmdline; then
+    echo "No KBS_URL or PASSPHRASE_PATH specified in kernel commandline"
+    exit 1
 fi
 
+passphrase_hex="$(kbs-client \
+                    --url "${KBS_URL}" \
+                    get-resource \
+                      --path "${PASSPHRASE_PATH}" | \
+                  base64 -d | xxd -p | tr -d "\n")"
+
+magic="$(echo -ne "${passphrase_hex}" | cut -c 1-8)"
+# "ENCP" magic
+if [ "${magic}" == "454e4350" ]; then
+    encp="$(echo -ne "${passphrase_hex}" | xxd -p -r)"
+    passphrase="$(encp-decoder "${encp}")"
+else
+    passphrase="${passphrase_hex}"
+fi
+
+echo -ne "${passphrase}" | xxd -p -r | cryptsetup open -d - /dev/vda1 root
 if [ $? -ne 0 ]; then
-    echo "luks2 open failed!!"
+    echo "Failed to open LUKS2 system volume"
     exec init
 fi
 
